---
- name: Gerenciando Ubuntu na nuvem Google Cloud
  hosts: GOOGLE
  gather_facts: no 
  tasks: 
  - name: Instalando pacotes default  
    apt:
      pkg:
      - git
      - gradle
      - openjdk-11-jdk-headless
      - httpd

